# Generated by Django 4.0.5 on 2022-06-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorsItems',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Quadratic',
            fields=[
                ('eq_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_value', models.FloatField(max_length=16)),
                ('b_value', models.FloatField(max_length=16)),
                ('c_value', models.FloatField(max_length=16)),
                ('result_1', models.FloatField(blank=True, max_length=16, null=True)),
                ('result_2', models.FloatField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
