# Generated by Django 4.0.5 on 2022-06-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_colorsitems_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorsitems',
            name='item_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
